kind: pipeline
type: docker
name: sv-socialtool


#trigger:
#  branch:
#  - master
pipeline:
  build: 
    image: plugins/docker
    settings:
      debug: true
      repo: tphoney/test
      tags: latest
      context: ./backend
      dockerfile: Dockerfile



  
