---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  branch:
    - main

steps:
  - name: Build Node Dependencies
    image: node
    commands:
      - cd backend
      - npm install
      - npm run build
  - name: Create and upload Docker Image
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      registry: registry.der-taenzer.net
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASS
      build_args:
       - BUILDKIT_INLINE_CACHE=1
      repo: registry.der-taenzer.net/tnz/eventverein-api
      tags:
        - latest
        - build-${DRONE_BUILD_NUMBER}
      dockerfile: ./backend/Dockerfile
      context: ./backend
  - name: Refresh Docker Stack
    image: plugins/webhook
    settings:
      urls: http://manager01.der-taenzer.net:9000/api/stacks/webhooks/543292b4-54cb-40e0-94f8-15cb8df825e6?BUILD_NR=${DRONE_BUILD_NUMBER}&BUILD_DATE=${DRONE_BUILD_CREATED}
