---
kind: pipeline
name: default

pipeline:
  test:
    image: plugins/docker
    volumes:
      - name: dockersock
        path: "/var/run/docker.sock" # Mandatory
    settings: 
      username: 12
      password: abc
      repo: tnz/test
      tags: 1.0
      dockerfile: ./backend/Dockerfile
    

