---
kind: pipeline
name: default

steps:
- name: test
  image: docker
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps -a

