version: "3.8"
services:
  app:
    build: ./backend/
    container_name: backend
    command: >-
      sh -c "
        apk add php82-pecl-xdebug && composer install ;\
        cp .docker/php.ini-development /etc/php82/php.ini ;\
        cp .docker/xdebug.ini /etc/php82/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/html:rw
    networks:
      - app_network
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    container_name: mysql
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
      - "33060:33060"
    expose:
      - 3306
      - 33060
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
