version: "3.8"
services:
  app:
    build: ./backend/
    container_name: backend
    command: >-
      sh -c "
        apk add php82-pecl-xdebug && composer install ;\
        cp .docker/php.ini-development /etc/php82/php.ini ;\
        cp .docker/xdebug.ini /etc/php82/conf.d/50_xdebug.ini ;\
        php artisan serve --host 0.0.0.0 --port 80"
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - ./backend:/var/www/html:rw
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
